version: "3.5"
services:

  portalsvc:
    image: ghcr.io/apogiatzis/ccsc-2022/portal-gun/validation:latest
    build: 
      context: ./setup/portal-svc
      dockerfile: Dockerfile
    restart: always

  validationsvc:
    image: ghcr.io/apogiatzis/ccsc-2022/portal-gun/core:latest
    build: 
      context: ./setup/validation-svc
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:3000
    links:
      - portalsvc

  portaldb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db

  mongo-seed:
    image: ghcr.io/apogiatzis/ccsc-2022/portal-gun/mongo-seed:latest
    build: 
      context: ./setup/mongo-seed
      dockerfile: Dockerfile
    links:
      - portaldb
