version: "3.7"

services:
  challenge:
    image: ghcr.io/apogiatzis/ccsc-2022/anatomy-park:latest
    restart: always
    ports:
      - 13373:13373
    build:
      context: ./setup
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"

