name: Build ans Push Challenges

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install ctfcli
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/apogiatzis/ctfcli
      
      - name: Challenge discovery
        id: challenge-discovery
        uses: ./.github/actions/discover-challenges
        with:
          base-dir: '.'

      - name: Docker challenge discovery
        id: docker-chall-discovery
        run: |
          IFS=' ' read -r -a chall_dirs <<< "${{ steps.challenge-discovery.outputs.dirs }}"
          for dir in "${chall_dirs[@]}"; do
              if [[ -f "${dir}/docker-compose.yml" ]]; then
                  dirs+=("${dir}")
              fi
          done
          echo "dirs=${dirs[*]}" >> "$GITHUB_OUTPUT"

      - name: Docker challenges list
        run: echo "${{ steps.docker-chall-discovery.outputs.dirs }}"

      - name: Create folder challenge hashes
        id: challenge-hashes
        run: |
          IFS=' ' read -r -a challenge_dirs <<< "${{ steps.docker-chall-discovery.outputs.dirs }}"
          for challenge_dir in "${challenge_dirs[@]}"; do
            hash=$(find $challenge_dir -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum)
            hashes+=("${hash}")
          done
          echo "hashes=${hashes[*]}" >> "$GITHUB_OUTPUT"
      
      - name: Docker challenges list
        run: echo "${{ steps.challenge-hashes.outputs.hashes }}"
      
      # - name: Build challenges
      #   run: |
      #     IFS=' ' read -r -a challenge_dirs <<< "${{ steps.docker-chall-discovery.outputs.dirs }}"
      #     for challenge_dir in "${challenge_dirs[@]}"; do
      #       docker compose -f $challenge_dir/docker-compose.yml build
      #     done
      
      # - name: Push challenges
      #   run: |
      #     IFS=' ' read -r -a challenge_dirs <<< "${{ steps.docker-chall-discovery.outputs.dirs }}"
      #     for challenge_dir in "${challenge_dirs[@]}"; do
      #       docker compose -f $challenge_dir/docker-compose.yml push
      #     done
