name: Lint Challenges

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find directories containing challenge.yml
        id: find-challenge-dirs
        run: |
          dirs=$(find . -name 'challenge.yml' -printf '%h\n' | sort -u)
          echo dirs="${dirs//$'\n'/,}" >> "$GITHUB_OUTPUT"

      - name: Show output
        run: echo "${{ steps.find-challenge-dirs.outputs.dirs }}"