name: Lint Challenges

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install ctfcli
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/apogiatzis/ctfcli

      - name: Find directories containing challenge.yml
        id: find-challenge-dirs
        run: |
          dirs=$(find . -name 'challenge.yml' -printf '%h\n' | sort -u)
          echo dirs="${dirs//$'\n'/ }" >> "$GITHUB_OUTPUT"

      - name: Show output
        run: echo "${{ steps.find-challenge-dirs.outputs.dirs }}"

      - name: Lint challenges
        run: |
          IFS=' ' read -r -a challenge_dirs <<< "${{ steps.find-challenge-dirs.outputs.dirs }}"
          for challenge_dir in "${challenge_dirs[@]}"; do
            ctf challenge lint $challenge_dir
          done