name: Challenge Pipeline


on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  build:
    uses: ./.github/workflows/build.yml
    needs: lint
  


